### PR TITLE
WIP: Pre-compiled wheel

### PR DESCRIPTION
**Pull request by rdbisme**

### CODE REVIEW

**Comment by 0x0L** [comment]
I'm not sure how to deal with binary wheel bc of the dep on `arrow` see https://github.com/0x0L/pgeon/issues/8
For python we want pgeon to use pyarrow libs

**Comment by rdbisme** [comment]
The Linux wheel here was working correctly last time I checked. It was correctly built and linked against `arrow` on `manylinux`. I had a strange error on Mac, and since I don't have a Mac anymore, I couldn't test it locally.

**Comment by 0x0L** [comment]
MacOS & linux builds on the pip_only branch but it's still using pyarrow conda-forge
Windows fails because libpq include dir is missing in setuptools cflags

**Comment by rdbisme** [comment]
> MacOS & linux builds on the pip_only branch but it's still using pyarrow conda-forge Windows fails because libpq include dir is missing in setuptools cflags

I think the wheel built using `pyarrow conda-forge` won't work on vanilla systems.

**Comment by 0x0L** [comment]
Yeah probably :) My issue is that the wheel built using `pyarrow pypi` does not work either

**Comment by rdbisme** [comment]
[pgeon-0.1.dev67+gc83c817.d20230219-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.zip](https://github.com/0x0L/pgeon/files/10777423/pgeon-0.1.dev67%2Bgc83c817.d20230219-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.zip)

Can you test this in a vanilla linux environment (so just create a virtual env, and install the wheel)? 

(just rename it removing the ` .zip`  extension)

**Comment by 0x0L** [comment]
That works. It's 80M of arrow libs for 1M of pgeon though

**Comment by rdbisme** [comment]
> That works. It's 80M of arrow libs for 1M of pgeon though
> 
> Where do you arrow libs you include in that wheel come from ? Not the pypi dist I think I'm starting to suspect that the libarrow bundled within pyarrow pypi wheels for linux is missing some components, compared to the arrow-cpp distribution or the macos wheel

The `ArrowPython`  bits are coming from `pyarrow`, the rest comes from the CentOS 7 distribution (because manylinux image I'm using is RHEL7 based) of Arrow: https://arrow.apache.org/install/

**Comment by rdbisme** [comment]
I agree that the `libarrow` in the `pyarrow` should work instead.

**Comment by rdbisme** [comment]
There's also a collision between the `_json` compiled extensions coming from `cpython` and the one coming from `_json.pyx` in pyarrow... 🥹

**Comment by rdbisme** [comment]
Ok, I managed to make it work: https://github.com/0x0L/pgeon/actions/runs/4219008290/jobs/7323975452

I need to tweak the `MACOS_DEPLOYMENT_TARGET` to account for the fact that Homebrew is lazy, and builds only for the version of Macos is installed on, but I should be on the good track.

**Comment by rdbisme** [comment]
@0x0L i can close this?

**Comment by 0x0L** [comment]
I think so. Main is still missing a few things like proper macos target and windows build

**Pull request closed without merging**
