### PR TITLE
:package: build: Relabel manylinux wheel ignoring pyarrow

### PR DESCRIPTION
**Pull request by rdbisme**

### CODE REVIEW

**Comment by rdbisme** [comment]
Probably I'd replace the `repair-wheel` script with a Python script, getting the libraries dynamically using `pa.get_libraries()` and the version from `pa.__version__` to build the ignore list.

**Comment by rdbisme** [comment]
https://pypi.org/project/pgeon/0.2.0a0/

**Comment by 0x0L** [comment]
Should I merge as is or do you want to add so code to inject your patch in repairwheel ?

**Comment by rdbisme** [comment]
I want to make the repairwheel independent of pyarrow version. I also opened a MR on auditwheel to support fnmatch... I'll merge once done.

**Pull request merged**
